### ISSUE TITLE
Version of Agda used for testing the repo

### ISSUE THREAD

**Issue by asr** [jpvillaisaza/abel#3]
Hi Juan,

In the README you wrote:

```
The Agda code was tested with Agda 2.3.2.2 and the Agda standard library 0.7. See src/Abel.agda.
```

I just tested the repo using Agda 2.5.1.1 and standard library 0.12. Please update the README and the `src/Abel.agda` file.

**Comment by asr** [comment]
CC'ing @elobove.

**Comment by jpvillaisaza** [comment]
@asr Thanks! I'll update the versions in a moment.

**Comment by asr** [comment]
Great, thanks!
